#h2 configuration

server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#external-api:
#  tvmaze:
#    name: "tvmaze-api"
#    url: "https://api.tvmaze.com"
#  lastfm:
#    name: "lastfm-api"
#    url: "http://ws.audioscrobbler.com/2.0"
